#! /bin/sh

# fcitx5
fcitx5 -d --replace &

# waybar
waybar &

# variety
variety &

# Notionfy
dunst &

# river-tag-overlay
river-tag-overlay &

# DPI
#way-displays &

# Follow
#follow &

# Email
#thunderbird &

# Discord
discord &

# RSS reader
fluent-reader &

# Screen shot
#obs &

# Steam
steam &

# Lutris
#lutris &

# Telegram
telegram-desktop &

# Numlock
numlockx on

# EQ
easyeffects &
