#! /bin/sh

# fcitx5
fcitx5 &

# waybar
waybar &

# variety
variety &

# set Background
swaybg -i ~/Pictures/ -m fill &

# mako 
mako &

# river-tag-overlay 
river-tag-overlay & 

# DPI
#way-displays &

# Follow
follow &

# Email
thunderbird &

# Discord
discord &

# RSS reader
fluent-reader &

#  Flameshot
#flameshot &

# Steam
steam &

# Lutris
#lutris &

