#! /bin/sh

riverctl spawn "$HOME/.config/river/set_env"

riverctl spawn "$HOME/.config/river/keymap"

riverctl spawn "$HOME/.config/river/autostart"

#riverctl spawn "$HOME/.config/river/set_background"


